export const paintureInfoGeneral: Object = {
	title: 'Malerei',
	headerBack: 'assets/works/painture/z.jpg'
};

export const paintureItmsInfo: Array<Object> = [
			{
				id: 1,
				name: 'Animal Brothers',
				imgUrl: 'assets/works/painture/a.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 1,
				available: true,
				size: '40x90 cm',
				material: 'óleo',
				year: 'agosto 2009',
				place: 'México'
			},
			{
				id: 2,
				name: 'Blue Leopard',
				imgUrl: 'assets/works/painture/c.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 2,
				available: true,
				size: '30x30 cm',
				material: 'canvas',
				year: 'agosto 2008',
				place: 'England'
			},
			{
				id: 3,
				name: 'El observador',
				imgUrl: 'assets/works/painture/d.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 3,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 4,
				name: 'CalacaFace',
				imgUrl: 'assets/works/painture/e.jpeg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 4,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'julio 2011',
				place: 'Holanda'
			},
			{
				id: 5,
				name: 'Tiger',
				imgUrl: 'assets/works/painture/f.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 5,
				available: true,
				size: '90x50 cm',
				material: 'óleo en tela',
				year: 'januer 2000',
				place: 'Guatemala'
			},
			{
				id: 6,
				name: 'Grüne Vogel',
				imgUrl: 'assets/works/painture/g.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 6,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'February 2008',
				place: 'Argentina'
			},
			{
				id: 7,
				name: 'Tiburón',
				imgUrl: 'assets/works/painture/h.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 7,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 8,
				name: 'Tzompantli 1',
				imgUrl: 'assets/works/painture/i.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 8,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 9,
				name: 'Tzompantli onColor',
				imgUrl: 'assets/works/painture/j.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 9,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 10,
				name: 'Cocodrilo Náhuatl',
				imgUrl: 'assets/works/painture/k.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 10,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 11,
				name: 'Conejo Lunar',
				imgUrl: 'assets/works/painture/l.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 11,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 12,
				name: 'Conejo en Rosa',
				imgUrl: 'assets/works/painture/m.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 12,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 13,
				name: 'Happy Mouse',
				imgUrl: 'assets/works/painture/n.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 13,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 14,
				name: 'La Danza',
				imgUrl: 'assets/works/painture/o.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 14,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 15,
				name: 'Death path',
				imgUrl: 'assets/works/painture/p.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 15,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 16,
				name: 'Cocodrile',
				imgUrl: 'assets/works/painture/q.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 16,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 17,
				name: 'Calendario y yo',
				imgUrl: 'assets/works/painture/r.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 17,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 18,
				name: 'Eyes',
				imgUrl: 'assets/works/painture/s.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 18,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 19,
				name: 'Fishes',
				imgUrl: 'assets/works/painture/t.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 19,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 20,
				name: 'Grüne Papagai',
				imgUrl: 'assets/works/painture/u.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 20,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 21,
				name: 'Rote und tot',
				imgUrl: 'assets/works/painture/v.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 21,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 22,
				name: 'TzompantliFront',
				imgUrl: 'assets/works/painture/w.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 22,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 23,
				name: 'Süsse Vorgangenheit',
				imgUrl: 'assets/works/painture/x.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 23,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 24,
				name: 'Blau Umwelt',
				imgUrl: 'assets/works/painture/y.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 24,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 25,
				name: 'Warhola Vogel',
				imgUrl: 'assets/works/painture/z.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 25,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 26,
				name: 'Easy trace',
				imgUrl: 'assets/works/painture/za.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 26,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 27,
				name: 'Weiße tot',
				imgUrl: 'assets/works/painture/zb.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 27,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 28,
				name: 'Purple Monkey',
				imgUrl: 'assets/works/painture/zc.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 28,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 29,
				name: 'Conejo rubio',
				imgUrl: 'assets/works/painture/zd.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 29,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 30,
				name: 'Papagai auf wieße',
				imgUrl: 'assets/works/painture/ze.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 30,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 31,
				name: 'Rock and surprise',
				imgUrl: 'assets/works/painture/zf.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 31,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 32,
				name: 'Battle',
				imgUrl: 'assets/works/painture/zg.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 32,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 33,
				name: 'Walk',
				imgUrl: 'assets/works/painture/zh.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 33,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 34,
				name: 'Stark Vogel',
				imgUrl: 'assets/works/painture/zj.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 34,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 35,
				name: 'Family',
				imgUrl: 'assets/works/painture/zk.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 35,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			},
			{
				id: 36,
				name: 'Hund',
				imgUrl: 'assets/works/painture/zl.jpg',
				description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio nemo recusandae saepe iure, commodi eligendi quae suscipit rem! Nostrum animi illo, consequatur aperiam nulla obcaecati cum quibusdam. Laudantium, esse accusamus?',
				priority: 36,
				available: true,
				size: '90x50 cm',
				material: 'óleo',
				year: 'november 2011',
				place: 'Australia'
			}
];